CREATE TABLE PLANE_TYPE
(MODEL VARCHAR(25) NOT NULL,CAPACITY INT(2),WEIGHT INT(2),
PRIMARY KEY(MODEL));

CREATE TABLE HANGAR
(NUMBER VARCHAR(5) NOT NULL,CAPACITY INT(2),LOCATION VARCHAR(3),
PRIMARY KEY(NUMBER)
);

CREATE TABLE CORPORATION
(NAME VARCHAR(25),ADDRESS VARCHAR(50),PHONE VARCHAR(10),
PRIMARY KEY(NAME)
);

CREATE TABLE PERSON
(SSN VARCHAR(10),ADDRESS VARCHAR(50),PHONE VARCHAR(10),NAME VARCHAR(25)
);